sudo: false

os:
  - osx
  - linux

language: cpp
compiler: clang

addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
      - clang

script:
  - ./gradlew makeNode
  - ./gradlew assemble
  - ./gradlew check
